[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-unwindlib=system",
  "-C", "link-arg=-Wl,-rpath,@executable_path/../Frameworks"
]

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-unwindlib=system",
  "-C", "link-arg=-Wl,-rpath,@executable_path/../Frameworks"
]
