# SPDX-License-Identifier: MIT OR Apache-2.0

[dist]
cargo-dist-version = "0.22.0"
targets = ["aarch64-apple-darwin"]
installers = ["dmg"]
apple-universal = false        # AS-only
sign-macos    = true           # ad-hoc if no cert
apple-notarize = false

[dist.dmg]
background = "assets/dmg_bg.png"
window-size = [660, 400]
icon-size   = 80
