[workspace]
resolver = "2"
members = [
    "sword_net",
    "shield_net",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"

[profile.release]
opt-level = "s"  # Optimize for size
lto = true
panic = "abort"