name: Release
permissions:
  "contents": "write"

# This task will run whenever you push a git tag that starts with v
on:
  push:
    tags:
      - 'v*'

jobs:
  build-dmg:
    runs-on: macos-latest
    env:
      CARGO_DIST_RELEASE_TARGETS: "universal2-apple-darwin"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Rust toolchain
        run: |
          rustup update stable
          rustup target add aarch64-apple-darwin x86_64-apple-darwin
          
      - name: Build universal2 binary
        run: |
          cargo build -p p2pgo-ui-egui --release --target aarch64-apple-darwin
          cargo build -p p2pgo-ui-egui --release --target x86_64-apple-darwin
          lipo -create \
            target/aarch64-apple-darwin/release/p2pgo-ui-egui \
            target/x86_64-apple-darwin/release/p2pgo-ui-egui \
            -output p2pgo-ui-egui-universal2
            
      - name: Bundle .app
        run: |
          mkdir -p "P2P Go.app/Contents/MacOS"
          mkdir -p "P2P Go.app/Contents/Resources"
          cp p2pgo-ui-egui-universal2 "P2P Go.app/Contents/MacOS/p2pgo-ui-egui"
          cp assets/appicon.icns "P2P Go.app/Contents/Resources/"
          codesign --deep --force --sign - "P2P Go.app"
          
      - name: Make DMG
        run: |
          brew install create-dmg
          create-dmg \
            --volname "P2P Go" \
            --window-pos 200 120 \
            --window-size 660 400 \
            --icon-size 80 \
            --icon "P2P Go.app" 180 170 \
            --app-drop-link 480 170 \
            --background "assets/dmg_bg.png" \
            "P2P Go.dmg" \
            .
            
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: "P2P Go.dmg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
