name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test-and-build:
    name: Test and Build macOS DMG
    runs-on: macos-14  # Use macOS 14 (Sonoma) with Apple Silicon
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
          
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        
      - name: Install create-dmg and dylibbundler
        run: |
          brew update
          brew install create-dmg
          brew install dylibbundler
          
      - name: Run tests
        env:
          CI_MODE: 1
        run: |
          echo "Running network relay tests"
          cargo test --features iroh -- network_relay
          echo "Running main test suite"
          cargo test --all --features iroh
          
      - name: Build DMG
        env:
          IROH_RELAY_MODE: default
        run: |
          echo "Building with relay mode: $IROH_RELAY_MODE"
          chmod +x scripts/dev_dmg.sh
          ./scripts/dev_dmg.sh
          
      - name: Read VERSION file
        id: get_version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
        
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            P2P Go.dmg
            P2P Go.dmg.sha256
          draft: false
          prerelease: false
          generate_release_notes: true
          name: P2P Go v${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
