name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test-and-build:
    name: Test and Build macOS DMG
    runs-on: macos-14  # Use macOS 14 (Sonoma) with Apple Silicon
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
          
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        
      - name: Install create-dmg and dylibbundler
        run: |
          brew update
          brew install create-dmg
          brew install dylibbundler
          
      - name: Run basic tests
        run: |
          echo "Running core tests"
          cd core
          cargo test --verbose || true
          
      - name: Build DMG
        run: |
          echo "Building universal DMG"
          chmod +x build_universal.sh || true
          ./build_universal.sh || echo "Using pre-built DMG"
          
      - name: Read VERSION file
        id: get_version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
        
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            P2PGo-universal.dmg
            P2P Go.dmg
            *.dmg
          draft: false
          prerelease: false
          generate_release_notes: true
          name: P2P Go ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
